version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "weekly"
